version: "3.9"
services:
  api:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  web:
    build: ./frontend
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
